{{- if and (.Values.serviceAccount.enabled) (.Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: {{- include "etcd-backup.labels" . | nindent 4 }}
{{- end }}
